Assessment factory XBlock implemented
hrvojevu/xblock-assessment-factory pull request #1
Opened 2016-10-13 12:11 UTC by hrvojevu

@marjev

2016-10-15 14:18 UTC, marjev requested changes
Dodaj neki plug-in koji ti na kraju svakog file-a dodaje prazan space. Fajlovi koje nekakav kompajler spaja u jedan, tipa sass, mogu biti krivo spojeni ako nema na kraju tog space-a.

Osim toga, dodaj u setup file da je ovaj XBlock pod MIT licencom. Pogledaj primjere drugih. Isto to mozes dodati i u README file. Pogledaj malo kako drugi XBlockovi imaju napravljen README file.

Mozemo u ponedjeljak skupa proci kroz komentare i kod, pa u slucaju nejasnoca ili pitanja, mozemo analizirati komentare. Neki komentari su samo pitanja jer mi nije bas bilo jasno.

2016-10-15 14:18 UTC, marjev commented on .gitignore
> +/assessment_factory/public/css/assessment_factory_edit.css
Brate, generaliziraj ovo, stavi: `*.css`

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
>  """TO-DO: Write a description of what this XBlock is."""
Moga si i napravit onda opis XBlocka 🗡

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
>      """
And again, samo dodaj opis XBlocka i sto cini. Pogledaj kako to rade u drugim XBlockovima.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +    has_score = True
Nemoj hardcodirat ovo.

Napravi nesto poput:

```
has_score = Boolean(
        display_name=_("Scored"),
        help=_("Select True if this component will receive a numerical score from the external LTI system."),
        default=False,
        scope=Scope.settings
    )
```

Neka se ovo radi u studiu, u zasebnom tabu. Dakle, neka se kroz checkbox gleda hoce li utjecati na ocjenu ili ne (has_score), a ako hoce neka onda profesor moze unijeti i koliki postotak ocjene nosi ovaj XBlock.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +        }
Jel ti treba ovo? Zar mu self ne mozes poslati direktno u Fragment?

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +        })
Jel ti treba prazni dictionary kao drugi parametar?

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
>      def student_view(self, context=None):
Poslozi metode unutar klase tako da idu prvo student_view, studio_view, pa nakon toga svi @XBlock.handleri, a na kraju (ako imas) neke utility metode i svojstva.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +        }
mozes odmah vratiti context dict. Kompliciras stvar time sto vracas dict unutar dicta.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +                        if self.item_state[item_id]['zone_id'] == zone['id']:
Ova dva if-a mozes spojiti ujedan i onda ispod imati samo jedan else. DRY.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +        return{
Umjesto da vracas ovdje vrijednosti, mozes odmah postaviti to u atribute instance `correct_items` i `incorrect_items`.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +        return{
Onda ti ova metoda moze sluziti da vraca True ili False, ako je doslo do promjene atributa, tj. ako je od zadnjeg submissiona bilo izmjena.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +                    self.correct_items = data['correct_items']
Ako ti gore navedena metoda `_get_correct_incorrect_items` vraca True ili False, tj. je li doslo do izmijene, mozes poziv te metode staviti kao uvjet provjere u `if`-u.
Dolje onda vracas incorrect_items i correct_items iz instance, ne iz data.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +                    self.correct_items = data['correct_items']
Onda ces i preimenovat `_get_correct_incorrect_items` u nesto smislenije cime ces izraziti namjenu metode.
Npr. `is_submission_changed`

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +            except NotImplementedError:
Kada i zasto ti se javlja `NotImplementedError`?

2016-10-15 14:18 UTC, marjev commented on assessment_factory/assessment_factory.py
> +        return float(correct_count) / float(total_count) * self.weight
ovo mozes napisati kao `float(correct_count/total_count*self.weight)`. Smanjujes broj pretvorbi.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/README.txt
> +This XBlock is using sass. Build assets after installing this XBlock.
Ovo prebaci u glavni README i napisi tocno koja naredba se treba unijeti kako bi se asseti izbuildali.
Osim toga, napisi bas step-by-step dokumentaciju kako se pravilno instalira XBlock. Pogledaj kako to rade na repozitorijima drugih XBlockova.

Nemoj da ljudi moraju previse googlati naokolo. Znas kakva je to tlaka.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/html/assessment_factory.html
> +		<i class="submit">Submit</i>
Identiraj ovo sto je unutar if-a da je lakse citati kod.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/html/assessment_factory_edit.html
> +</div>
Samo malo popravi indentaciju. Previse ti se ovo razbizalo.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +            data: '{}',
Jel ti data treba biti string ili moze biti cisti dictionary?

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +                    $(".other-container").append('<i class="submit">Submit</i>');
Napravi pomocne funkcije za ovo. Nesto u stilu jedne funkcije koja ce appendati u `other-container` sadrzaj.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +                    $(".check").text("Check (" + data.ctx.retry_count + " left)");
Pokusaj za ovo koristiti [Underscore string library](http://gabceb.github.io/underscore.string.site/#sprintf). Pokusaj ne raditi konkatenaciju stringova, nego formatiranje stringa za ispis.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +                }
Razmisli o koristenju Underscora za ovo. On ima each koji je malo citljiviji, a sto se tice ovog selektora, mozes napisati pomocnu funkciju koja ce na temelju parametra vratiti string selector #{vrijednost}.

Imas to i u petlji ispod. Dakle isti komentar.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +                for(var key in data.correct_items){
Isto kao i povise.

Dobro bi bilo DRY-at, dakle imati jednu funckiju koja ce na temelju liste podataka proci elementima doma i dodati potrebnu klasu. Sve promjenjive dijelove parametriziraj.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +                }, 5000);
Zasto ti treba ovaj timeout?

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +        var $element = $("#" + item_id);
Dakle, opet, ovo mozes izdvojiti u jednu funkciju i koristiti nesto tipa Underscore string.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +        initDroppable();
Ove tri linije imas vec gore pozvane, tako da mozes ovo pretvoriti u pomocnu funckiju i zvati po potrebi.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory.js
> +    }
Razmisli o DRY-anju ovoga. Imas dijelova koji se ponavljaju.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/js/src/assessment_factory_edit.js
> +};
1) Isto kao i u prethodnom fileu, potreban je DRY. Sve sto se ponavlja izdvojiti u zasebnu funkciju. Stvari koje su zajednicke medu fileovima izdvoji u zasebni js file koji ces pozivati na oba template-a (student i studio).
2) Smanji razmake na 1. Dovoljan je 1 izmedu dviju funkcija.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/sass/assessment_factory.scss
> +}
Smanji broj tabova za indentaciju. Dovoljna su u sassu 2.

2016-10-15 14:18 UTC, marjev commented on assessment_factory/public/sass/assessment_factory.scss
> +	}
Jel ti bas treba important?

2016-10-15 14:33 UTC, hrvojevu commented on .gitignore
> +/assessment_factory/public/css/assessment_factory_edit.css
nisan stavia *.css zato da mi ne ignora css file od jquery-ui i fontawesome. al dobro, mogu dodat bower ili neki klinac za te dependencie...

2016-10-15 14:33 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
>  """TO-DO: Write a description of what this XBlock is."""
okay xD

2016-10-15 14:34 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
> +    has_score = True
Ovo sam u onom drag and drop xblocku vidia, mislia san da samo treba stavit ovako, ako se zeli ocjenjivanje

2016-10-15 14:35 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
> +        })
because of reasons...

2016-10-15 14:35 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
> +        }
netreba :D, mogu i HOĆU!

2016-10-15 14:36 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
> +                    self.correct_items = data['correct_items']
👍

2016-10-15 14:37 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
> +            except NotImplementedError:
ovo san kao i "has_score" skupia iz d&d xblocka, nisan ima error, al eto preventivno...

2016-10-15 14:38 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
> +        return float(correct_count) / float(total_count) * self.weight
yep

2016-10-15 14:40 UTC, hrvojevu commented on assessment_factory/assessment_factory.py
> +                        if self.item_state[item_id]['zone_id'] == zone['id']:
224. i 225.? ok. mislim da san i bia stavija u 1 al je bilo presiroko, pa san radi preglednosti stavia 2

2016-10-15 14:41 UTC, hrvojevu commented on assessment_factory/public/README.txt
> +This XBlock is using sass. Build assets after installing this XBlock.
hmm, nisam ni razmislja da bi neko moga koristit, pa nisan ni stavlja upute..

2016-10-15 14:42 UTC, marjev commented on .gitignore
> +/assessment_factory/public/css/assessment_factory_edit.css
mozes onda ignorirat sve css fileove iz nekog foldera u koji te buildane css fileove misliš spremat, možemo u ponediljak vidit

2016-10-15 14:43 UTC, marjev commented on assessment_factory/assessment_factory.py
> +    has_score = True
ovako ćeš omogućit profesoru da sam odluči želi li ocjenjivanje ili samo koristit xblock za vježbu.

2016-10-15 14:43 UTC, marjev commented on assessment_factory/assessment_factory.py
> +        })
:)

2016-10-15 14:44 UTC, marjev commented on assessment_factory/assessment_factory.py
> +            except NotImplementedError:
aha, mogu provat vidit zašto su oni stavili, al generalno ako nemaš nekih očitih iznimki, onda ti i ne triba. ne vidim šta može bit neimplementirano tu

2016-10-15 14:45 UTC, marjev commented on assessment_factory/assessment_factory.py
> +                        if self.item_state[item_id]['zone_id'] == zone['id']:
da, možeš ti razbit uvjet u više linija, al imat jedan if i jedan else, da bude pregledno, a i dalje manji broj if-ova i else-a.

2016-10-15 14:46 UTC, marjev commented on assessment_factory/public/README.txt
> +This XBlock is using sass. Build assets after installing this XBlock.
Cilj mi je da se hvalimo kasnije s ovim :)

2016-10-15 14:47 UTC, hrvojevu commented on assessment_factory/public/js/src/assessment_factory.js
> +            data: '{}',
ne salje nista u ovom ajaxu, tako da je ovo greska.

2016-10-15 14:47 UTC, hrvojevu commented on assessment_factory/public/js/src/assessment_factory.js
> +                    $(".other-container").append('<i class="submit">Submit</i>');
okay

2016-10-15 14:50 UTC, hrvojevu commented on assessment_factory/public/js/src/assessment_factory.js
> +                }, 5000);
to san stavia da sam makne klase, da ne moran posli razmisljat i sam micat :D

2016-10-15 14:52 UTC, hrvojevu commented on assessment_factory/public/sass/assessment_factory.scss
> +	}
treba je , jer je iz nekog razloga prioritizira lms-ov css

2016-10-21 14:14 UTC, hrvojevu commented
@marjev evo commit sa fixevima

2016-11-14 11:30 UTC, merged